"""create_all_tables

Revision ID: 21c36b3a2038
Revises: 
Create Date: 2026-02-11 23:55:19.521412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21c36b3a2038'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_prompt_hash'), 'prompts', ['prompt_hash'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('cloud_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size_kb', sa.BigInteger(), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_videos_identifier'), 'videos', ['identifier'], unique=True)
    op.create_index(op.f('ix_videos_source_url'), 'videos', ['source_url'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('word_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segment_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('number_of_words', sa.Integer(), nullable=True),
    sa.Column('number_of_segments', sa.Integer(), nullable=True),
    sa.Column('transcription_service', sa.String(length=50), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcripts_full_text_gin', 'transcripts', [sa.literal_column("to_tsvector('english', full_text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_transcripts_video_id'), 'transcripts', ['video_id'], unique=True)
    op.create_table('generation_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('min_moment_length', sa.Float(), nullable=True),
    sa.Column('max_moment_length', sa.Float(), nullable=True),
    sa.Column('min_moments', sa.Integer(), nullable=True),
    sa.Column('max_moments', sa.Integer(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_configs_config_hash'), 'generation_configs', ['config_hash'], unique=True)
    op.create_index(op.f('ix_generation_configs_model'), 'generation_configs', ['model'], unique=False)
    op.create_index(op.f('ix_generation_configs_operation_type'), 'generation_configs', ['operation_type'], unique=False)
    op.create_index(op.f('ix_generation_configs_prompt_id'), 'generation_configs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_generation_configs_transcript_id'), 'generation_configs', ['transcript_id'], unique=False)
    op.create_table('moments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=20), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('is_refined', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('generation_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_moment_end_after_start'),
    sa.ForeignKeyConstraint(['generation_config_id'], ['generation_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['moments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_moments_timestamps', 'moments', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_moments_identifier'), 'moments', ['identifier'], unique=True)
    op.create_index(op.f('ix_moments_is_refined'), 'moments', ['is_refined'], unique=False)
    op.create_index(op.f('ix_moments_parent_id'), 'moments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_moments_video_id'), 'moments', ['video_id'], unique=False)
    op.create_table('pipeline_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('generation_config_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_moments_generated', sa.Integer(), nullable=True),
    sa.Column('total_clips_created', sa.Integer(), nullable=True),
    sa.Column('error_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_config_id'], ['generation_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_history_generation_config_id'), 'pipeline_history', ['generation_config_id'], unique=False)
    op.create_index(op.f('ix_pipeline_history_identifier'), 'pipeline_history', ['identifier'], unique=True)
    op.create_index(op.f('ix_pipeline_history_started_at'), 'pipeline_history', ['started_at'], unique=False)
    op.create_index(op.f('ix_pipeline_history_status'), 'pipeline_history', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_history_video_id'), 'pipeline_history', ['video_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moment_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('cloud_url', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('padding_left', sa.Float(), nullable=False),
    sa.Column('padding_right', sa.Float(), nullable=False),
    sa.Column('file_size_kb', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_clip_end_after_start'),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_moment_id'), 'clips', ['moment_id'], unique=True)
    op.create_index(op.f('ix_clips_video_id'), 'clips', ['video_id'], unique=False)
    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('cloud_url', sa.Text(), nullable=False),
    sa.Column('file_size_kb', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(video_id IS NOT NULL AND clip_id IS NULL) OR (video_id IS NULL AND clip_id IS NOT NULL)', name='check_thumbnail_video_or_clip'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_thumbnails_clip_id_unique', 'thumbnails', ['clip_id'], unique=True, postgresql_where='clip_id IS NOT NULL')
    op.create_index('idx_thumbnails_video_id_unique', 'thumbnails', ['video_id'], unique=True, postgresql_where='video_id IS NOT NULL')
    op.create_index(op.f('ix_thumbnails_clip_id'), 'thumbnails', ['clip_id'], unique=False)
    op.create_index(op.f('ix_thumbnails_video_id'), 'thumbnails', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnails_video_id'), table_name='thumbnails')
    op.drop_index(op.f('ix_thumbnails_clip_id'), table_name='thumbnails')
    op.drop_index('idx_thumbnails_video_id_unique', table_name='thumbnails', postgresql_where='video_id IS NOT NULL')
    op.drop_index('idx_thumbnails_clip_id_unique', table_name='thumbnails', postgresql_where='clip_id IS NOT NULL')
    op.drop_table('thumbnails')
    op.drop_index(op.f('ix_clips_video_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_moment_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_pipeline_history_video_id'), table_name='pipeline_history')
    op.drop_index(op.f('ix_pipeline_history_status'), table_name='pipeline_history')
    op.drop_index(op.f('ix_pipeline_history_started_at'), table_name='pipeline_history')
    op.drop_index(op.f('ix_pipeline_history_identifier'), table_name='pipeline_history')
    op.drop_index(op.f('ix_pipeline_history_generation_config_id'), table_name='pipeline_history')
    op.drop_table('pipeline_history')
    op.drop_index(op.f('ix_moments_video_id'), table_name='moments')
    op.drop_index(op.f('ix_moments_parent_id'), table_name='moments')
    op.drop_index(op.f('ix_moments_is_refined'), table_name='moments')
    op.drop_index(op.f('ix_moments_identifier'), table_name='moments')
    op.drop_index('idx_moments_timestamps', table_name='moments')
    op.drop_table('moments')
    op.drop_index(op.f('ix_generation_configs_transcript_id'), table_name='generation_configs')
    op.drop_index(op.f('ix_generation_configs_prompt_id'), table_name='generation_configs')
    op.drop_index(op.f('ix_generation_configs_operation_type'), table_name='generation_configs')
    op.drop_index(op.f('ix_generation_configs_model'), table_name='generation_configs')
    op.drop_index(op.f('ix_generation_configs_config_hash'), table_name='generation_configs')
    op.drop_table('generation_configs')
    op.drop_index(op.f('ix_transcripts_video_id'), table_name='transcripts')
    op.drop_index('idx_transcripts_full_text_gin', table_name='transcripts', postgresql_using='gin')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_videos_source_url'), table_name='videos')
    op.drop_index(op.f('ix_videos_identifier'), table_name='videos')
    op.drop_index(op.f('ix_videos_created_at'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_prompts_prompt_hash'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
