"""make_pipeline_history_gen_config_nullable

Revision ID: a5fe25dd5741
Revises: 2e33e2fef5f2
Create Date: 2026-02-22 01:52:46.356538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fe25dd5741'
down_revision: Union[str, Sequence[str], None] = '2e33e2fef5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_history', 'generation_config_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('pipeline_history_generation_config_id_fkey'), 'pipeline_history', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_history', 'generation_configs', ['generation_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_history', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_history_generation_config_id_fkey'), 'pipeline_history', 'generation_configs', ['generation_config_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pipeline_history', 'generation_config_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
